/**
 * AUTO-GENERATED by `pnpm run db:types` (supabase gen types). Do not hand-edit.
 * Named aliases (UserRole, Profile, ...) live in `database.types.ts`, which
 * re-exports from this file.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      attendance_sessions: {
        Row: {
          created_at: string
          created_by: string
          dojo_id: string
          event_id: string
          expires_at: string
          geo_enabled: boolean
          id: string
          lat: number | null
          lng: number | null
          token_hash: string
        }
        Insert: {
          created_at?: string
          created_by: string
          dojo_id: string
          event_id: string
          expires_at: string
          geo_enabled?: boolean
          id?: string
          lat?: number | null
          lng?: number | null
          token_hash: string
        }
        Update: {
          created_at?: string
          created_by?: string
          dojo_id?: string
          event_id?: string
          expires_at?: string
          geo_enabled?: boolean
          id?: string
          lat?: number | null
          lng?: number | null
          token_hash?: string
        }
        Relationships: [
          {
            foreignKeyName: "attendance_sessions_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "attendance_sessions_dojo_id_fkey"
            columns: ["dojo_id"]
            isOneToOne: false
            referencedRelation: "dojos"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "attendance_sessions_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
        ]
      }
      attendances: {
        Row: {
          confirmed_at: string | null
          confirmed_by: string | null
          created_at: string
          dojo_id: string
          effective_hours: number
          event_id: string
          event_role: Database["public"]["Enums"]["event_role"]
          id: string
          method: Database["public"]["Enums"]["attendance_method"]
          notes: string | null
          profile_id: string
          status: Database["public"]["Enums"]["attendance_status"]
          updated_at: string
          weighted_hours: number
        }
        Insert: {
          confirmed_at?: string | null
          confirmed_by?: string | null
          created_at?: string
          dojo_id: string
          effective_hours: number
          event_id: string
          event_role?: Database["public"]["Enums"]["event_role"]
          id?: string
          method?: Database["public"]["Enums"]["attendance_method"]
          notes?: string | null
          profile_id: string
          status?: Database["public"]["Enums"]["attendance_status"]
          updated_at?: string
          weighted_hours: number
        }
        Update: {
          confirmed_at?: string | null
          confirmed_by?: string | null
          created_at?: string
          dojo_id?: string
          effective_hours?: number
          event_id?: string
          event_role?: Database["public"]["Enums"]["event_role"]
          id?: string
          method?: Database["public"]["Enums"]["attendance_method"]
          notes?: string | null
          profile_id?: string
          status?: Database["public"]["Enums"]["attendance_status"]
          updated_at?: string
          weighted_hours?: number
        }
        Relationships: [
          {
            foreignKeyName: "attendances_confirmed_by_fkey"
            columns: ["confirmed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "attendances_dojo_id_fkey"
            columns: ["dojo_id"]
            isOneToOne: false
            referencedRelation: "dojos"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "attendances_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "attendances_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      communication_recipients: {
        Row: {
          communication_id: string
          created_at: string
          id: string
          profile_id: string
          read_at: string | null
        }
        Insert: {
          communication_id: string
          created_at?: string
          id?: string
          profile_id: string
          read_at?: string | null
        }
        Update: {
          communication_id?: string
          created_at?: string
          id?: string
          profile_id?: string
          read_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "communication_recipients_communication_id_fkey"
            columns: ["communication_id"]
            isOneToOne: false
            referencedRelation: "communications"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "communication_recipients_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      communications: {
        Row: {
          body: string
          created_at: string
          dojo_id: string
          id: string
          is_draft: boolean
          published_at: string | null
          sent_by: string
          target_audience: string
          title: string
          updated_at: string
        }
        Insert: {
          body: string
          created_at?: string
          dojo_id: string
          id?: string
          is_draft?: boolean
          published_at?: string | null
          sent_by: string
          target_audience?: string
          title: string
          updated_at?: string
        }
        Update: {
          body?: string
          created_at?: string
          dojo_id?: string
          id?: string
          is_draft?: boolean
          published_at?: string | null
          sent_by?: string
          target_audience?: string
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "communications_dojo_id_fkey"
            columns: ["dojo_id"]
            isOneToOne: false
            referencedRelation: "dojos"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "communications_sent_by_fkey"
            columns: ["sent_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      dojo_role_assignments: {
        Row: {
          assigned_by: string
          can_manage_payments: boolean
          can_manage_resources: boolean
          can_view_payments: boolean
          created_at: string
          dojo_id: string
          id: string
          label: string
          profile_id: string
          updated_at: string
        }
        Insert: {
          assigned_by: string
          can_manage_payments?: boolean
          can_manage_resources?: boolean
          can_view_payments?: boolean
          created_at?: string
          dojo_id: string
          id?: string
          label: string
          profile_id: string
          updated_at?: string
        }
        Update: {
          assigned_by?: string
          can_manage_payments?: boolean
          can_manage_resources?: boolean
          can_view_payments?: boolean
          created_at?: string
          dojo_id?: string
          id?: string
          label?: string
          profile_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "dojo_role_assignments_assigned_by_fkey"
            columns: ["assigned_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "dojo_role_assignments_dojo_id_fkey"
            columns: ["dojo_id"]
            isOneToOne: false
            referencedRelation: "dojos"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "dojo_role_assignments_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      dojos: {
        Row: {
          academic_year_end_day: number
          academic_year_end_month: number
          academic_year_start_day: number
          academic_year_start_month: number
          address: string | null
          checkin_auto_confirm: boolean
          checkin_geofence_enabled: boolean
          checkin_lat: number | null
          checkin_lng: number | null
          checkin_radius_m: number | null
          conductor_weight: number
          created_at: string
          default_event_weight: number
          federation: string
          id: string
          max_absences_default: number | null
          name: string
          printed_qr_enabled: boolean
          require_attendance_confirmation: boolean
          updated_at: string
        }
        Insert: {
          academic_year_end_day?: number
          academic_year_end_month?: number
          academic_year_start_day?: number
          academic_year_start_month?: number
          address?: string | null
          checkin_auto_confirm?: boolean
          checkin_geofence_enabled?: boolean
          checkin_lat?: number | null
          checkin_lng?: number | null
          checkin_radius_m?: number | null
          conductor_weight?: number
          created_at?: string
          default_event_weight?: number
          federation?: string
          id?: string
          max_absences_default?: number | null
          name: string
          printed_qr_enabled?: boolean
          require_attendance_confirmation?: boolean
          updated_at?: string
        }
        Update: {
          academic_year_end_day?: number
          academic_year_end_month?: number
          academic_year_start_day?: number
          academic_year_start_month?: number
          address?: string | null
          checkin_auto_confirm?: boolean
          checkin_geofence_enabled?: boolean
          checkin_lat?: number | null
          checkin_lng?: number | null
          checkin_radius_m?: number | null
          conductor_weight?: number
          created_at?: string
          default_event_weight?: number
          federation?: string
          id?: string
          max_absences_default?: number | null
          name?: string
          printed_qr_enabled?: boolean
          require_attendance_confirmation?: boolean
          updated_at?: string
        }
        Relationships: []
      }
      event_grade_exceptions: {
        Row: {
          created_at: string
          event_id: string
          granted_by: string
          id: string
          profile_id: string
        }
        Insert: {
          created_at?: string
          event_id: string
          granted_by: string
          id?: string
          profile_id: string
        }
        Update: {
          created_at?: string
          event_id?: string
          granted_by?: string
          id?: string
          profile_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "event_grade_exceptions_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "event_grade_exceptions_granted_by_fkey"
            columns: ["granted_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "event_grade_exceptions_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      events: {
        Row: {
          conductor_profile_id: string | null
          created_at: string
          description: string | null
          dojo_id: string
          duration_hours: number
          ends_at: string
          event_weight: number
          exam_target_grade: Database["public"]["Enums"]["grade_type"] | null
          grade_filter_max: Database["public"]["Enums"]["grade_type"] | null
          grade_filter_min: Database["public"]["Enums"]["grade_type"] | null
          id: string
          instructor_name: string | null
          is_cancelled: boolean
          location: string | null
          project_id: string | null
          starts_at: string
          template_id: string | null
          title: string
          type: Database["public"]["Enums"]["event_type"]
          updated_at: string
        }
        Insert: {
          conductor_profile_id?: string | null
          created_at?: string
          description?: string | null
          dojo_id: string
          duration_hours: number
          ends_at: string
          event_weight?: number
          exam_target_grade?: Database["public"]["Enums"]["grade_type"] | null
          grade_filter_max?: Database["public"]["Enums"]["grade_type"] | null
          grade_filter_min?: Database["public"]["Enums"]["grade_type"] | null
          id?: string
          instructor_name?: string | null
          is_cancelled?: boolean
          location?: string | null
          project_id?: string | null
          starts_at: string
          template_id?: string | null
          title: string
          type: Database["public"]["Enums"]["event_type"]
          updated_at?: string
        }
        Update: {
          conductor_profile_id?: string | null
          created_at?: string
          description?: string | null
          dojo_id?: string
          duration_hours?: number
          ends_at?: string
          event_weight?: number
          exam_target_grade?: Database["public"]["Enums"]["grade_type"] | null
          grade_filter_max?: Database["public"]["Enums"]["grade_type"] | null
          grade_filter_min?: Database["public"]["Enums"]["grade_type"] | null
          id?: string
          instructor_name?: string | null
          is_cancelled?: boolean
          location?: string | null
          project_id?: string | null
          starts_at?: string
          template_id?: string | null
          title?: string
          type?: Database["public"]["Enums"]["event_type"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "events_conductor_profile_id_fkey"
            columns: ["conductor_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "events_dojo_id_fkey"
            columns: ["dojo_id"]
            isOneToOne: false
            referencedRelation: "dojos"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "events_template_id_fkey"
            columns: ["template_id"]
            isOneToOne: false
            referencedRelation: "lesson_templates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "fk_events_project"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      exam_requirements: {
        Row: {
          created_at: string
          dojo_id: string
          id: string
          is_nomination: boolean
          min_age: number | null
          min_hours: number
          min_months_from_prev: number
          notes: string | null
          target_grade: Database["public"]["Enums"]["grade_type"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          dojo_id: string
          id?: string
          is_nomination?: boolean
          min_age?: number | null
          min_hours: number
          min_months_from_prev: number
          notes?: string | null
          target_grade: Database["public"]["Enums"]["grade_type"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          dojo_id?: string
          id?: string
          is_nomination?: boolean
          min_age?: number | null
          min_hours?: number
          min_months_from_prev?: number
          notes?: string | null
          target_grade?: Database["public"]["Enums"]["grade_type"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "exam_requirements_dojo_id_fkey"
            columns: ["dojo_id"]
            isOneToOne: false
            referencedRelation: "dojos"
            referencedColumns: ["id"]
          },
        ]
      }
      glossary_entries: {
        Row: {
          category: string | null
          created_at: string
          definition: string
          dojo_id: string
          id: string
          min_grade: Database["public"]["Enums"]["grade_type"] | null
          reading: string | null
          sort_order: number | null
          term: string
          updated_at: string
        }
        Insert: {
          category?: string | null
          created_at?: string
          definition: string
          dojo_id: string
          id?: string
          min_grade?: Database["public"]["Enums"]["grade_type"] | null
          reading?: string | null
          sort_order?: number | null
          term: string
          updated_at?: string
        }
        Update: {
          category?: string | null
          created_at?: string
          definition?: string
          dojo_id?: string
          id?: string
          min_grade?: Database["public"]["Enums"]["grade_type"] | null
          reading?: string | null
          sort_order?: number | null
          term?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "glossary_entries_dojo_id_fkey"
            columns: ["dojo_id"]
            isOneToOne: false
            referencedRelation: "dojos"
            referencedColumns: ["id"]
          },
        ]
      }
      grade_history: {
        Row: {
          created_at: string
          dojo_id: string
          exam_date: string | null
          exam_event_id: string | null
          granted_by: string | null
          id: string
          new_grade: Database["public"]["Enums"]["grade_type"]
          notes: string | null
          outcome: Database["public"]["Enums"]["exam_outcome"]
          previous_grade: Database["public"]["Enums"]["grade_type"] | null
          profile_id: string
          total_hours_at_change: number | null
        }
        Insert: {
          created_at?: string
          dojo_id: string
          exam_date?: string | null
          exam_event_id?: string | null
          granted_by?: string | null
          id?: string
          new_grade: Database["public"]["Enums"]["grade_type"]
          notes?: string | null
          outcome?: Database["public"]["Enums"]["exam_outcome"]
          previous_grade?: Database["public"]["Enums"]["grade_type"] | null
          profile_id: string
          total_hours_at_change?: number | null
        }
        Update: {
          created_at?: string
          dojo_id?: string
          exam_date?: string | null
          exam_event_id?: string | null
          granted_by?: string | null
          id?: string
          new_grade?: Database["public"]["Enums"]["grade_type"]
          notes?: string | null
          outcome?: Database["public"]["Enums"]["exam_outcome"]
          previous_grade?: Database["public"]["Enums"]["grade_type"] | null
          profile_id?: string
          total_hours_at_change?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "grade_history_dojo_id_fkey"
            columns: ["dojo_id"]
            isOneToOne: false
            referencedRelation: "dojos"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "grade_history_exam_event_id_fkey"
            columns: ["exam_event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "grade_history_granted_by_fkey"
            columns: ["granted_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "grade_history_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      journals: {
        Row: {
          content: string
          created_at: string
          dojo_id: string
          entry_date: string
          event_id: string | null
          id: string
          profile_id: string
          title: string | null
          updated_at: string
        }
        Insert: {
          content: string
          created_at?: string
          dojo_id: string
          entry_date?: string
          event_id?: string | null
          id?: string
          profile_id: string
          title?: string | null
          updated_at?: string
        }
        Update: {
          content?: string
          created_at?: string
          dojo_id?: string
          entry_date?: string
          event_id?: string | null
          id?: string
          profile_id?: string
          title?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "journals_dojo_id_fkey"
            columns: ["dojo_id"]
            isOneToOne: false
            referencedRelation: "dojos"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "journals_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "journals_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      lesson_templates: {
        Row: {
          created_at: string
          day_of_week: number
          dojo_id: string
          duration_hours: number
          end_time: string
          grade_filter_max: Database["public"]["Enums"]["grade_type"] | null
          grade_filter_min: Database["public"]["Enums"]["grade_type"] | null
          id: string
          is_active: boolean
          season_label: string | null
          start_time: string
          updated_at: string
          valid_from: string | null
          valid_to: string | null
        }
        Insert: {
          created_at?: string
          day_of_week: number
          dojo_id: string
          duration_hours?: number
          end_time: string
          grade_filter_max?: Database["public"]["Enums"]["grade_type"] | null
          grade_filter_min?: Database["public"]["Enums"]["grade_type"] | null
          id?: string
          is_active?: boolean
          season_label?: string | null
          start_time: string
          updated_at?: string
          valid_from?: string | null
          valid_to?: string | null
        }
        Update: {
          created_at?: string
          day_of_week?: number
          dojo_id?: string
          duration_hours?: number
          end_time?: string
          grade_filter_max?: Database["public"]["Enums"]["grade_type"] | null
          grade_filter_min?: Database["public"]["Enums"]["grade_type"] | null
          id?: string
          is_active?: boolean
          season_label?: string | null
          start_time?: string
          updated_at?: string
          valid_from?: string | null
          valid_to?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "lesson_templates_dojo_id_fkey"
            columns: ["dojo_id"]
            isOneToOne: false
            referencedRelation: "dojos"
            referencedColumns: ["id"]
          },
        ]
      }
      membership_status: {
        Row: {
          aikikai_card_status: string
          aikikai_expiry: string | null
          created_at: string
          dojo_fee_paid_until: string | null
          dojo_id: string
          id: string
          profile_id: string
          updated_at: string
        }
        Insert: {
          aikikai_card_status?: string
          aikikai_expiry?: string | null
          created_at?: string
          dojo_fee_paid_until?: string | null
          dojo_id: string
          id?: string
          profile_id: string
          updated_at?: string
        }
        Update: {
          aikikai_card_status?: string
          aikikai_expiry?: string | null
          created_at?: string
          dojo_fee_paid_until?: string | null
          dojo_id?: string
          id?: string
          profile_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "membership_status_dojo_id_fkey"
            columns: ["dojo_id"]
            isOneToOne: false
            referencedRelation: "dojos"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "membership_status_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          body: string
          channel: string
          created_at: string
          dojo_id: string
          id: string
          profile_id: string
          read_at: string | null
          sent_at: string | null
          status: string
          title: string
          type: string
        }
        Insert: {
          body: string
          channel: string
          created_at?: string
          dojo_id: string
          id?: string
          profile_id: string
          read_at?: string | null
          sent_at?: string | null
          status?: string
          title: string
          type: string
        }
        Update: {
          body?: string
          channel?: string
          created_at?: string
          dojo_id?: string
          id?: string
          profile_id?: string
          read_at?: string | null
          sent_at?: string | null
          status?: string
          title?: string
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_dojo_id_fkey"
            columns: ["dojo_id"]
            isOneToOne: false
            referencedRelation: "dojos"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          booklet_type: string | null
          can_conduct: boolean
          created_at: string
          current_grade: Database["public"]["Enums"]["grade_type"]
          date_of_birth: string | null
          dojo_id: string
          enrollment_date: string
          first_name: string
          id: string
          is_active: boolean
          is_guest: boolean
          last_name: string
          medical_cert_expiry: string | null
          medical_cert_file_path: string | null
          phone: string | null
          photo_url: string | null
          role: Database["public"]["Enums"]["user_role"]
          updated_at: string
          user_id: string
        }
        Insert: {
          booklet_type?: string | null
          can_conduct?: boolean
          created_at?: string
          current_grade?: Database["public"]["Enums"]["grade_type"]
          date_of_birth?: string | null
          dojo_id: string
          enrollment_date?: string
          first_name: string
          id?: string
          is_active?: boolean
          is_guest?: boolean
          last_name: string
          medical_cert_expiry?: string | null
          medical_cert_file_path?: string | null
          phone?: string | null
          photo_url?: string | null
          role?: Database["public"]["Enums"]["user_role"]
          updated_at?: string
          user_id: string
        }
        Update: {
          booklet_type?: string | null
          can_conduct?: boolean
          created_at?: string
          current_grade?: Database["public"]["Enums"]["grade_type"]
          date_of_birth?: string | null
          dojo_id?: string
          enrollment_date?: string
          first_name?: string
          id?: string
          is_active?: boolean
          is_guest?: boolean
          last_name?: string
          medical_cert_expiry?: string | null
          medical_cert_file_path?: string | null
          phone?: string | null
          photo_url?: string | null
          role?: Database["public"]["Enums"]["user_role"]
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "profiles_dojo_id_fkey"
            columns: ["dojo_id"]
            isOneToOne: false
            referencedRelation: "dojos"
            referencedColumns: ["id"]
          },
        ]
      }
      project_grade_exceptions: {
        Row: {
          created_at: string
          granted_by: string
          id: string
          profile_id: string
          project_id: string
        }
        Insert: {
          created_at?: string
          granted_by: string
          id?: string
          profile_id: string
          project_id: string
        }
        Update: {
          created_at?: string
          granted_by?: string
          id?: string
          profile_id?: string
          project_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "project_grade_exceptions_granted_by_fkey"
            columns: ["granted_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "project_grade_exceptions_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "project_grade_exceptions_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      project_members: {
        Row: {
          enrolled_at: string
          enrolled_by: string
          external_email: string | null
          external_name: string | null
          id: string
          is_active: boolean
          profile_id: string | null
          project_id: string
        }
        Insert: {
          enrolled_at?: string
          enrolled_by: string
          external_email?: string | null
          external_name?: string | null
          id?: string
          is_active?: boolean
          profile_id?: string | null
          project_id: string
        }
        Update: {
          enrolled_at?: string
          enrolled_by?: string
          external_email?: string | null
          external_name?: string | null
          id?: string
          is_active?: boolean
          profile_id?: string | null
          project_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "project_members_enrolled_by_fkey"
            columns: ["enrolled_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "project_members_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "project_members_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      projects: {
        Row: {
          access_level: Database["public"]["Enums"]["access_level"]
          created_at: string
          description: string | null
          dojo_id: string
          external_responsible: string | null
          grade_filter_max: Database["public"]["Enums"]["grade_type"] | null
          grade_filter_min: Database["public"]["Enums"]["grade_type"] | null
          id: string
          is_active: boolean
          is_main_course: boolean
          name: string
          responsible_profile_id: string | null
          updated_at: string
        }
        Insert: {
          access_level?: Database["public"]["Enums"]["access_level"]
          created_at?: string
          description?: string | null
          dojo_id: string
          external_responsible?: string | null
          grade_filter_max?: Database["public"]["Enums"]["grade_type"] | null
          grade_filter_min?: Database["public"]["Enums"]["grade_type"] | null
          id?: string
          is_active?: boolean
          is_main_course?: boolean
          name: string
          responsible_profile_id?: string | null
          updated_at?: string
        }
        Update: {
          access_level?: Database["public"]["Enums"]["access_level"]
          created_at?: string
          description?: string | null
          dojo_id?: string
          external_responsible?: string | null
          grade_filter_max?: Database["public"]["Enums"]["grade_type"] | null
          grade_filter_min?: Database["public"]["Enums"]["grade_type"] | null
          id?: string
          is_active?: boolean
          is_main_course?: boolean
          name?: string
          responsible_profile_id?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "projects_dojo_id_fkey"
            columns: ["dojo_id"]
            isOneToOne: false
            referencedRelation: "dojos"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "projects_responsible_profile_id_fkey"
            columns: ["responsible_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      push_tokens: {
        Row: {
          created_at: string
          expo_token: string
          id: string
          platform: string
          profile_id: string
        }
        Insert: {
          created_at?: string
          expo_token: string
          id?: string
          platform: string
          profile_id: string
        }
        Update: {
          created_at?: string
          expo_token?: string
          id?: string
          platform?: string
          profile_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "push_tokens_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      resources: {
        Row: {
          created_at: string
          created_by: string
          description: string | null
          dojo_id: string
          file_path: string | null
          id: string
          mime_type: string | null
          target_grade: Database["public"]["Enums"]["grade_type"] | null
          title: string
          type: Database["public"]["Enums"]["resource_type"]
          updated_at: string
          url: string | null
        }
        Insert: {
          created_at?: string
          created_by: string
          description?: string | null
          dojo_id: string
          file_path?: string | null
          id?: string
          mime_type?: string | null
          target_grade?: Database["public"]["Enums"]["grade_type"] | null
          title: string
          type: Database["public"]["Enums"]["resource_type"]
          updated_at?: string
          url?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string
          description?: string | null
          dojo_id?: string
          file_path?: string | null
          id?: string
          mime_type?: string | null
          target_grade?: Database["public"]["Enums"]["grade_type"] | null
          title?: string
          type?: Database["public"]["Enums"]["resource_type"]
          updated_at?: string
          url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "resources_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "resources_dojo_id_fkey"
            columns: ["dojo_id"]
            isOneToOne: false
            referencedRelation: "dojos"
            referencedColumns: ["id"]
          },
        ]
      }
      secretary_permissions: {
        Row: {
          can_confirm_attendance: boolean
          can_manage_calendar: boolean
          can_manage_events: boolean
          can_manage_glossary: boolean
          can_manage_projects: boolean
          can_manage_resources: boolean
          can_manage_suspensions: boolean
          can_manage_users: boolean
          can_pre_register_emails: boolean
          can_send_communications: boolean
          can_verify_exam_requirements: boolean
          can_view_all_attendance: boolean
          can_view_all_profiles: boolean
          created_at: string
          dojo_id: string
          id: string
          profile_id: string
          updated_at: string
        }
        Insert: {
          can_confirm_attendance?: boolean
          can_manage_calendar?: boolean
          can_manage_events?: boolean
          can_manage_glossary?: boolean
          can_manage_projects?: boolean
          can_manage_resources?: boolean
          can_manage_suspensions?: boolean
          can_manage_users?: boolean
          can_pre_register_emails?: boolean
          can_send_communications?: boolean
          can_verify_exam_requirements?: boolean
          can_view_all_attendance?: boolean
          can_view_all_profiles?: boolean
          created_at?: string
          dojo_id: string
          id?: string
          profile_id: string
          updated_at?: string
        }
        Update: {
          can_confirm_attendance?: boolean
          can_manage_calendar?: boolean
          can_manage_events?: boolean
          can_manage_glossary?: boolean
          can_manage_projects?: boolean
          can_manage_resources?: boolean
          can_manage_suspensions?: boolean
          can_manage_users?: boolean
          can_pre_register_emails?: boolean
          can_send_communications?: boolean
          can_verify_exam_requirements?: boolean
          can_view_all_attendance?: boolean
          can_view_all_profiles?: boolean
          created_at?: string
          dojo_id?: string
          id?: string
          profile_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "secretary_permissions_dojo_id_fkey"
            columns: ["dojo_id"]
            isOneToOne: false
            referencedRelation: "dojos"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "secretary_permissions_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      suspension_periods: {
        Row: {
          created_at: string
          dojo_id: string
          end_date: string
          id: string
          is_recurring: boolean
          name: string
          recurring_day_start: number | null
          recurring_month_start: number | null
          start_date: string
        }
        Insert: {
          created_at?: string
          dojo_id: string
          end_date: string
          id?: string
          is_recurring?: boolean
          name: string
          recurring_day_start?: number | null
          recurring_month_start?: number | null
          start_date: string
        }
        Update: {
          created_at?: string
          dojo_id?: string
          end_date?: string
          id?: string
          is_recurring?: boolean
          name?: string
          recurring_day_start?: number | null
          recurring_month_start?: number | null
          start_date?: string
        }
        Relationships: [
          {
            foreignKeyName: "suspension_periods_dojo_id_fkey"
            columns: ["dojo_id"]
            isOneToOne: false
            referencedRelation: "dojos"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      get_user_dojo_ids: { Args: never; Returns: string[] }
      get_user_profile_ids: { Args: never; Returns: string[] }
      is_head_master_of: { Args: { target_dojo_id: string }; Returns: boolean }
    }
    Enums: {
      access_level: "public" | "dojo_members" | "filtered"
      attendance_method: "roll_call" | "qr_code" | "direct_entry"
      attendance_status: "registered" | "confirmed" | "rejected"
      event_role: "participant" | "conductor"
      event_type:
        | "lesson"
        | "lesson_extra"
        | "stage"
        | "exam"
        | "workshop"
        | "gathering"
      exam_outcome: "passed" | "failed" | "nomination"
      grade_type:
        | "none"
        | "kyu_6"
        | "kyu_5"
        | "kyu_4"
        | "kyu_3"
        | "kyu_2"
        | "kyu_1"
        | "dan_1"
        | "dan_2"
        | "dan_3"
        | "dan_4"
        | "dan_5"
        | "dan_6"
        | "dan_7"
      resource_type: "didactic" | "personal"
      user_role: "head_master" | "secretary" | "aikidoka" | "guest"
      workshop_frequency: "one_time" | "periodic" | "fundamental"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {
      access_level: ["public", "dojo_members", "filtered"],
      attendance_method: ["roll_call", "qr_code", "direct_entry"],
      attendance_status: ["registered", "confirmed", "rejected"],
      event_role: ["participant", "conductor"],
      event_type: [
        "lesson",
        "lesson_extra",
        "stage",
        "exam",
        "workshop",
        "gathering",
      ],
      exam_outcome: ["passed", "failed", "nomination"],
      grade_type: [
        "none",
        "kyu_6",
        "kyu_5",
        "kyu_4",
        "kyu_3",
        "kyu_2",
        "kyu_1",
        "dan_1",
        "dan_2",
        "dan_3",
        "dan_4",
        "dan_5",
        "dan_6",
        "dan_7",
      ],
      resource_type: ["didactic", "personal"],
      user_role: ["head_master", "secretary", "aikidoka", "guest"],
      workshop_frequency: ["one_time", "periodic", "fundamental"],
    },
  },
} as const

